id: P1879C768
initial_creation_type: input
source_metadata:
  title: Nyoshul Lungtok Series
  language: en
  description: 'Texts by the great Dzogchen master Nyoshul Lungtok Tenpe Nyima (smyo
    shul lung rtogs bstan pa''i nyi ma, 1829–1901/2):'
  volume:
    f16ddbae69e0436780b16633402d94ca:
      title: Bodhicitta Aspiration
      parent: Prayers and Practices
    5e9cf122fd034b1aa1fbcd6e2bb27995:
      title: Prayer to Avalokiteśvara
      parent: Prayers and Practices
created_at: '2022-03-01T01:06:42.461254'
last_modified_at: '2022-03-01T01:06:42.461260'
